services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: itemsdb
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_NAME=itemsdb
      - DB_PORT=5432
    volumes:
      - ..:/app
      - /app/node_modules
    networks:
          - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge